# บรรทัดนี้ต้องอยู่ชิดซ้ายสุด
backend:
  # ย่อหน้าด้วย 2 space
  name: git-gateway
  branch: main

# บรรทัดนี้ต้องอยู่ชิดซ้ายสุด
media_folder: "imges"
public_folder: "/imges"

# บรรทัดนี้ต้องอยู่ชิดซ้ายสุด
collections:
  # ย่อหน้าด้วย 2 space
  - name: "pages"
    label: "Page Content"
    files:
      # ย่อหน้าด้วย 4 space
      - file: "index.html"
        label: "Homepage"
        name: "homepage"
        fields: # ย่อหน้าด้วย 6 space
          # ย่อหน้าด้วย 8 space
          - { label: "หัวข้อหลัก", name: "hero_title", widget: "string" }
          - { label: "คำโปรย", name: "hero_subtitle", widget: "text" }
          - { label: "โลโก้กลางหน้า", name: "hero_logo", widget: "image" }
